// export const actionTypes = {

// FETCH_CATEGORIES: 'FETCH_CATEGORIES',
// FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
// FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',
// FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
// FETCH_USER_ERROR: 'FETCH_USER_ERROR',
// SET_TOKEN: 'SET_TOKEN',
// LOGOUT_USER: 'LOGOUT_USER',
// SEARCH_ACTIVE: 'SEARCH_ACTIVE',
// SEARCH_INACTIVE: 'SEARCH_INACTIVE',
// SEARCH_SONGS_PENDING: 'SEARCH_SONGS_PENDING',
// SEARCH_SONGS_SUCCESS: 'SEARCH_SONGS_SUCCESS',
// SEARCH_SONGS_ERROR: 'SEARCH_SONGS_ERROR',

// }
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SEARCH_ACTIVE = 'SEARCH_ACTIVE';
export const SEARCH_INACTIVE = 'SEARCH_INACTIVE';
export const SEARCH_SONGS_PENDING = 'SEARCH_SONGS_PENDING';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';
export const SEARCH_SONGS_ERROR = 'SEARCH_SONGS_ERROR';
export const FETCH_PLAYLIST_MENU_PENDING = 'FETCH_PLAYLIST_MENU_PENDING';
export const FETCH_PLAYLIST_MENU_SUCCESS = 'FETCH_PLAYLIST_MENU_SUCCESS';
export const FETCH_PLAYLIST_MENU_ERROR = 'FETCH_PLAYLIST_MENU_ERROR';
export const ADD_PLAYLIST_ITEM = 'ADD_PLAYLIST_ITEM';
export const FETCH_PLAYLIST_SONGS_PENDING = 'FETCH_PLAYLIST_SONGS_PENDING';
export const FETCH_PLAYLIST_SONGS_SUCCESS = 'FETCH_PLAYLIST_SONGS_SUCCESS';
export const FETCH_PLAYLIST_SONGS_ERROR = 'FETCH_PLAYLIST_SONGS_ERROR';
export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE';
export const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
export const FETCH_FEATURED_ERROR = 'FETCH_FEATURED_ERROR';







